package boundary;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.time.Duration;
import java.util.*;


import com.github.lgooddatepicker.components.DatePicker;
import com.github.lgooddatepicker.components.DatePickerSettings;
import controller.IntesaSport;
import entity.*;

import java.time.LocalDate;
import java.util.List;

public class FormCreaSessioneAllenamento extends JFrame {

    private JLabel LabelSessioneAllenamento;
    private JComboBox comboAtleti;
    private DatePicker datePicker1;
    private JSpinner spinnerDurata;
    private JTextArea txtDescrizione;
    private JList listaEsercizi;
    private JButton aggiungiEsercizioButton;
    private JButton salvaSessioneButton;
    private JPanel contentPane;
    private JTextField txtTitoloSessione;
    private JButton eliminaEsercizioButton;
    private JLabel txtInfo;
    //Lo uso per avere la lista degli esercii aggiunti che si aggiorna
    private DefaultListModel<String> modelloListaEsercizi = new DefaultListModel<>();
    private List<EsercizioDettaglioDTO> listaEserciziSessione = new ArrayList<>();

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        contentPane = new JPanel();
        contentPane.setLayout(new GridLayoutManager(14, 11, new Insets(0, 0, 0, 0), -1, -1));
        contentPane.setMaximumSize(new Dimension(700, 10500));
        contentPane.setMinimumSize(new Dimension(500, 450));
        contentPane.setPreferredSize(new Dimension(500, 450));
        LabelSessioneAllenamento = new JLabel();
        LabelSessioneAllenamento.setText("Sessione Allenamento");
        contentPane.add(LabelSessioneAllenamento, new GridConstraints(0, 1, 1, 8, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label1 = new JLabel();
        label1.setText("Atleta");
        contentPane.add(label1, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        comboAtleti = new JComboBox();
        contentPane.add(comboAtleti, new GridConstraints(2, 2, 1, 8, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label2 = new JLabel();
        label2.setText("Data");
        contentPane.add(label2, new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label3 = new JLabel();
        label3.setText("Durata Prevista - Minuti");
        contentPane.add(label3, new GridConstraints(4, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label4 = new JLabel();
        label4.setText("Descrizione");
        contentPane.add(label4, new GridConstraints(5, 1, 1, 9, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label5 = new JLabel();
        label5.setText("Lista Esercizi");
        contentPane.add(label5, new GridConstraints(8, 1, 1, 9, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        contentPane.add(spacer1, new GridConstraints(4, 10, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        final Spacer spacer2 = new Spacer();
        contentPane.add(spacer2, new GridConstraints(4, 9, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        final Spacer spacer3 = new Spacer();
        contentPane.add(spacer3, new GridConstraints(7, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        contentPane.add(datePicker1, new GridConstraints(3, 5, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        contentPane.add(spinnerDurata, new GridConstraints(4, 5, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JSeparator separator1 = new JSeparator();
        contentPane.add(separator1, new GridConstraints(11, 0, 1, 11, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        salvaSessioneButton = new JButton();
        salvaSessioneButton.setBorderPainted(false);
        salvaSessioneButton.setText("Salva Sessione");
        contentPane.add(salvaSessioneButton, new GridConstraints(13, 1, 1, 9, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JScrollPane scrollPane1 = new JScrollPane();
        contentPane.add(scrollPane1, new GridConstraints(6, 1, 1, 9, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        txtDescrizione = new JTextArea();
        txtDescrizione.setLineWrap(true);
        txtDescrizione.setRows(4);
        txtDescrizione.setWrapStyleWord(true);
        scrollPane1.setViewportView(txtDescrizione);
        final Spacer spacer4 = new Spacer();
        contentPane.add(spacer4, new GridConstraints(4, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        final Spacer spacer5 = new Spacer();
        contentPane.add(spacer5, new GridConstraints(4, 3, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        final Spacer spacer6 = new Spacer();
        contentPane.add(spacer6, new GridConstraints(4, 7, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        final JScrollPane scrollPane2 = new JScrollPane();
        contentPane.add(scrollPane2, new GridConstraints(9, 1, 1, 9, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        listaEsercizi = new JList();
        listaEsercizi.setVisibleRowCount(4);
        scrollPane2.setViewportView(listaEsercizi);
        final JLabel label6 = new JLabel();
        label6.setText("Titolo Sessione");
        contentPane.add(label6, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        txtTitoloSessione = new JTextField();
        contentPane.add(txtTitoloSessione, new GridConstraints(1, 2, 1, 8, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        aggiungiEsercizioButton = new JButton();
        aggiungiEsercizioButton.setText("Aggiungi Esercizio");
        contentPane.add(aggiungiEsercizioButton, new GridConstraints(10, 5, 1, 5, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        eliminaEsercizioButton = new JButton();
        eliminaEsercizioButton.setText("Elimina Esercizio");
        contentPane.add(eliminaEsercizioButton, new GridConstraints(10, 1, 1, 4, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        txtInfo = new JLabel();
        txtInfo.setText("   ");
        contentPane.add(txtInfo, new GridConstraints(12, 1, 1, 9, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }

    private void createUIComponents() {
        // TODO: place custom component creation code here
        DatePickerSettings settings = new DatePickerSettings();
        datePicker1 = new DatePicker(settings);
        settings.setDateRangeLimits(LocalDate.now(), null);
        SpinnerModel spinnerDurata = new SpinnerNumberModel(0, 0, 3000, 1);
        this.spinnerDurata = new JSpinner(spinnerDurata);
    }

    //COSTRUTTORE
    public FormCreaSessioneAllenamento() {
        $$$setupUI$$$();

        this.setContentPane(contentPane);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.pack();
        this.setMinimumSize(new Dimension(600, 450));

        popolaComboAtleti();
        listaEsercizi.setModel(modelloListaEsercizi);
        aggiungiEsercizioButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                //Apro la finestra per aggiungere l'esercizio alla pressione del pulsante "Aggiungi Esercizio"
                FormAggiungiEsercizioAllaSessione popup = new FormAggiungiEsercizioAllaSessione();

                // La finestra è in attesa del popupesercizio
                popup.addWindowListener(new WindowAdapter() {
                    @Override
                    public void windowClosed(WindowEvent windowEvent) {

                        // aggiunta esercizio
                        if (popup.isConfermato()) {

                            EsercizioDettaglioDTO dto = popup.getDettaglioCreato();

                            // riga nella lista JList
                            String riga = dto.getNomeEx() + " - Ripetizioni: " + dto.getRipetizioni() + " - Durata: " + dto.getDurata().toMinutes() + " min";
                            modelloListaEsercizi.addElement(riga);

                            //aggiungo l'esercizio nell'ArrayList che verrà usato per creare poi le associazioni
                            listaEserciziSessione.add(dto);

                            //cambio la scritta sopra il pulsante per comunicare con l'utente
                            txtInfo.setForeground(new Color(0, 128, 0)); // Colore Verde
                            txtInfo.setText("Esercizio '" + dto.getNomeEx() + "' aggiunto.");

                        }
                    }
                });

                popup.setVisible(true);
            }

        });

        salvaSessioneButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String titoloSessione = txtTitoloSessione.getText();
                Atleta atletaSelezionato = (Atleta) comboAtleti.getSelectedItem();
                LocalDate dataSelezionata = datePicker1.getDate();
                int durata = (Integer) spinnerDurata.getValue();
                String descrizione = txtDescrizione.getText();

                SessioneDTO sessioneDaCreare = new SessioneDTO(
                        null,
                        titoloSessione,
                        descrizione,
                        dataSelezionata,
                        Duration.ofMinutes(durata),
                        StatoSessione.ASSEGNATA,
                        listaEserciziSessione
                );

                if (atletaSelezionato == null || dataSelezionata == null || titoloSessione.isEmpty()) {
                    JOptionPane.showMessageDialog(
                            null,
                            "Inserire Titolo, Atleta e Data!",
                            "Errore", JOptionPane.INFORMATION_MESSAGE);
                    return;
                }

                if (listaEserciziSessione.isEmpty()) {
                    JOptionPane.showMessageDialog(
                            null,
                            "Inserisci almeno un esercizio",
                            "Errore", JOptionPane.WARNING_MESSAGE);
                    return;
                }

                boolean successo = IntesaSport.creaNuovaSessione(
                        sessioneDaCreare,
                        atletaSelezionato.getEmail()
                );

                if (successo) {
                    txtInfo.setForeground(new Color(0, 128, 0));
                    txtInfo.setText("Sessione Creata Con Successo");
                    JOptionPane.showMessageDialog(
                            null,
                            "Sessione creata e salvata con successo!",
                            "Sessione Creata", JOptionPane.INFORMATION_MESSAGE);
                    // svuoto i campi per inserire una nuova sessione
                    listaEserciziSessione.clear();
                    modelloListaEsercizi.clear();
                    txtDescrizione.setText("");
                    txtTitoloSessione.setText("");
                    comboAtleti.setSelectedIndex(-1);
                    datePicker1.setDate(null);
                    spinnerDurata.setValue(0);
                } else {
                    txtInfo.setForeground(new Color(128, 0, 0));
                    txtInfo.setText("Sessione non creata - Riprovare");
                    JOptionPane.showMessageDialog(
                            null,
                            "Errore durante il salvataggio nel database.",
                            "Errore", JOptionPane.ERROR_MESSAGE);
                }

            }
        });
        eliminaEsercizioButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                int indiceSelezionato = listaEsercizi.getSelectedIndex();

                // bisogna obbligatoriamente selezionare un esercizio da togliere dalla lista
                if (indiceSelezionato == -1) {
                    JOptionPane.showMessageDialog(
                            FormCreaSessioneAllenamento.this,
                            "Seleziona un esercizio dalla lista per poterlo rimuovere.",
                            "Nessuna selezione",
                            JOptionPane.WARNING_MESSAGE
                    );
                    return;
                }

                // Rimuove l'oggetto DTO dalla struttura dati che verrà passata al Controller
                listaEserciziSessione.remove(indiceSelezionato);

                // Rimuove la stringa dal modello visivo per aggiornare la GUI
                modelloListaEsercizi.remove(indiceSelezionato);

                //cambio la scritta sopra il pulsante per comunicare con l'utente
                txtInfo.setForeground(new Color(128, 0, 0)); // Colore Verde
                txtInfo.setText("Esercizio rimosso.");
            }
        });
    }

    private void popolaComboAtleti() {

        comboAtleti.removeAllItems();

        List<Atleta> listaAtleti = IntesaSport.visualizzaAtletiAssociati();

        // Inserisce gli atleti nella tendina.
        // Grazie al toString() che hai fatto, si vedranno i nomi!
        if (listaAtleti != null) {
            for (Atleta a : listaAtleti) {
                comboAtleti.addItem(a);
            }
        }
    }


    /*


    // MAIN PROVA_______________________________________________________________________________________________________________
    public static void main(String[] args) {
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                FormCreaSessioneAllenamento form = new FormCreaSessioneAllenamento();
                form.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                form.setMinimumSize(new Dimension(350, 400));
                form.setLocationRelativeTo(null);
                form.setVisible(true);
            }
        });
    }

    */


}


