package boundary;

import controller.IntesaSport;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;


//Cercando su google ho aggiunto "extends javax.swing.JFrame" per poter avere un pop-up dalla schermata precedente

public class FormCreaEsercizio extends javax.swing.JDialog {

    private JPanel contentPane;
    private JTextField txtNome;
    private JButton salvaButton;
    private JLabel LabelIntro;
    private JLabel LabelName;
    private JLabel LabelDescrizione;
    private JTextArea txtDescrizione;
    //mi servirà per passare il nome dell'esercizio appena creato al form che chiamerà questo form.
    private String nomeEsercizioCreato = null;

    public FormCreaEsercizio() {

        this.setContentPane(contentPane);
        this.pack();

        salvaButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String nomeEsercizio = txtNome.getText().trim();
                String descrizione = txtDescrizione.getText().trim();

                //Controllo che entrambi i campi siano pieni

                if (nomeEsercizio.isEmpty() || descrizione.isEmpty()) {
                    JOptionPane.showMessageDialog(
                            FormCreaEsercizio.this,
                            "Errore: è necessario compilare tutti i campi!",
                            "Errore",
                            JOptionPane.INFORMATION_MESSAGE
                    );
                    return;
                }

                if (nomeEsercizio.length() > 100) {
                    JOptionPane.showMessageDialog(
                            FormCreaEsercizio.this,
                            "Il nome dell'esercizio è troppo lungo (Max 100 caratteri).",
                            "Errore", JOptionPane.INFORMATION_MESSAGE);
                    return;
                }

                //Se l'esercizio è già presente nel database il boolean sarà falso

                boolean salvataggioEsercizio = IntesaSport.creaEsercizio(nomeEsercizio, descrizione);

                if (!salvataggioEsercizio) {
                    JOptionPane.showMessageDialog(
                            FormCreaEsercizio.this,
                            "Errore: Un esercizio con questo NOME è già presente!",
                            "Esercizio già presente",
                            JOptionPane.INFORMATION_MESSAGE
                    );
                    return;
                }

                if (salvataggioEsercizio) {
                    JOptionPane.showMessageDialog(
                            FormCreaEsercizio.this,
                            "Esercizio creato con successo",
                            "Esercizio Creato",
                            JOptionPane.INFORMATION_MESSAGE
                    );

                    //Salvo il nome del nuovo esercizio così da poterlo cercare nel FormAggiungiEsercizioAllaSessione
                    FormCreaEsercizio.this.nomeEsercizioCreato = nomeEsercizio;

                    //Voglio che la finestra si chiuda automaticamente
                    //dopo aver creato con successo un esercizio
                    // e aver dato l'OK sulla finestra
                    FormCreaEsercizio.this.dispose();
                }

            }
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPane = new JPanel();
        contentPane.setLayout(new GridLayoutManager(12, 4, new Insets(0, 0, 0, 0), -1, -1));
        contentPane.setMaximumSize(new Dimension(280, 250));
        contentPane.setMinimumSize(new Dimension(280, 250));
        contentPane.setPreferredSize(new Dimension(280, 250));
        contentPane.setVisible(true);
        contentPane.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.black), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        LabelIntro = new JLabel();
        LabelIntro.setText("Inserisci i dati del nuovo esercizio da creare");
        contentPane.add(LabelIntro, new GridConstraints(1, 1, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        LabelName = new JLabel();
        LabelName.setText("Nome");
        contentPane.add(LabelName, new GridConstraints(3, 1, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        LabelDescrizione = new JLabel();
        LabelDescrizione.setText("Descrizione");
        contentPane.add(LabelDescrizione, new GridConstraints(6, 1, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        txtNome = new JTextField();
        txtNome.setHorizontalAlignment(0);
        contentPane.add(txtNome, new GridConstraints(4, 0, 1, 4, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, new Dimension(280, -1), new Dimension(280, -1), new Dimension(280, -1), 0, false));
        salvaButton = new JButton();
        salvaButton.setText("Salva");
        contentPane.add(salvaButton, new GridConstraints(10, 1, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        contentPane.add(spacer1, new GridConstraints(9, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, 1, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(-1, 10), null, 0, false));
        final Spacer spacer2 = new Spacer();
        contentPane.add(spacer2, new GridConstraints(11, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, 1, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(-1, 10), null, 0, false));
        final Spacer spacer3 = new Spacer();
        contentPane.add(spacer3, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, 1, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(-1, 10), null, 0, false));
        final Spacer spacer4 = new Spacer();
        contentPane.add(spacer4, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, 1, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(-1, 10), null, 0, false));
        final Spacer spacer5 = new Spacer();
        contentPane.add(spacer5, new GridConstraints(5, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, 1, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(-1, 10), null, 0, false));
        final JScrollPane scrollPane1 = new JScrollPane();
        contentPane.add(scrollPane1, new GridConstraints(7, 0, 2, 4, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        txtDescrizione = new JTextArea();
        txtDescrizione.setLineWrap(true);
        txtDescrizione.setMaximumSize(new Dimension(250, 250));
        txtDescrizione.setRows(4);
        txtDescrizione.setText("");
        txtDescrizione.setWrapStyleWord(true);
        scrollPane1.setViewportView(txtDescrizione);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }

    //Serve a passare il nome del nuovo esercizio ad altre classi
    public String getNomeEsercizioCreato(){
        return this.nomeEsercizioCreato;
    }

     /* //MAIN PER PROVARE LA CLASSE ____________________________________________________________________________

    public static void main(String[] args) {
        javax.swing.SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                FormCreaEsercizio form = new FormCreaEsercizio();
                form.setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);
                form.setMinimumSize(new java.awt.Dimension(350, 250));
                form.setLocationRelativeTo(null);
                form.setVisible(true);
            }
        });


    }

    */

}
