package boundary;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class FormIntesaSport {
    private JPanel contentPane;
    private JButton cercaSessioniButton;
    private JButton creaSessioneButton;
    private JButton registraPrestazioniButton;
    private JButton creaEsercizioButton;

    private JFrame cercaSessioniFrame;
    private JFrame registraPrestazioniFrame;
    private JFrame creaSessioniFrame;

    public FormIntesaSport() {
        cercaSessioniButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

                if (cercaSessioniFrame == null || !cercaSessioniFrame.isDisplayable()) {


                    formCercaSessioniConFiltro formInserimento = new formCercaSessioniConFiltro();


                    cercaSessioniFrame = formInserimento.apriFormCercaSessioni();

                    cercaSessioniFrame.setLocationRelativeTo(null);

                    cercaSessioniFrame.setVisible(true);


                } else {

                    cercaSessioniFrame.toFront();
                    cercaSessioniFrame.requestFocus();

                }
            }
        });

        registraPrestazioniButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

                if (registraPrestazioniFrame == null || !registraPrestazioniFrame.isDisplayable()) {


                    formRegistraPrestazioni formRegistraP = new formRegistraPrestazioni();


                    registraPrestazioniFrame = formRegistraP.apriFormRegistraPrestazioni();

                    registraPrestazioniFrame.setLocationRelativeTo(null);

                    registraPrestazioniFrame.setVisible(true);


                } else {

                    registraPrestazioniFrame.toFront();
                    registraPrestazioniFrame.requestFocus();

                }
            }
        });

        creaSessioneButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

                if (creaSessioniFrame == null || !creaSessioniFrame.isDisplayable()) {


                    FormCreaSessioneAllenamento formCreaS = new FormCreaSessioneAllenamento();


                    creaSessioniFrame = formCreaS.apriFormCreaSessioni();

                    creaSessioniFrame.setLocationRelativeTo(null);

                    creaSessioniFrame.setVisible(true);


                } else {

                    registraPrestazioniFrame.toFront();
                    registraPrestazioniFrame.requestFocus();

                }
            }
        });
    }

    public static void main(String[] args) {

        JFrame frame = new JFrame("Homepage Intesa Sport");

        FormIntesaSport mainFrame = new FormIntesaSport();

        frame.setContentPane(mainFrame.contentPane);

        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setSize(1000, 1200);
        frame.setResizable(false);
        frame.pack();
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);


    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPane = new JPanel();
        contentPane.setLayout(new GridLayoutManager(3, 9, new Insets(0, 0, 0, 0), -1, -1));
        contentPane.setMaximumSize(new Dimension(600, 300));
        contentPane.setMinimumSize(new Dimension(600, 300));
        contentPane.setPreferredSize(new Dimension(600, 200));
        cercaSessioniButton = new JButton();
        cercaSessioniButton.setText("Cerca sessioni");
        contentPane.add(cercaSessioniButton, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(-1, 100), null, 0, false));
        creaSessioneButton = new JButton();
        creaSessioneButton.setText("Crea sessione");
        contentPane.add(creaSessioneButton, new GridConstraints(1, 7, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(-1, 100), null, 0, false));
        registraPrestazioniButton = new JButton();
        registraPrestazioniButton.setText("Registra prestazioni");
        contentPane.add(registraPrestazioniButton, new GridConstraints(1, 3, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(-1, 100), null, 0, false));
        final Spacer spacer1 = new Spacer();
        contentPane.add(spacer1, new GridConstraints(1, 8, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, new Dimension(20, -1), null, 0, false));
        final Spacer spacer2 = new Spacer();
        contentPane.add(spacer2, new GridConstraints(1, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(20, -1), null, 0, false));
        final Spacer spacer3 = new Spacer();
        contentPane.add(spacer3, new GridConstraints(1, 6, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(20, -1), null, 0, false));
        final Spacer spacer4 = new Spacer();
        contentPane.add(spacer4, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, new Dimension(20, -1), null, 0, false));
        final Spacer spacer5 = new Spacer();
        contentPane.add(spacer5, new GridConstraints(2, 3, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        final Spacer spacer6 = new Spacer();
        contentPane.add(spacer6, new GridConstraints(0, 3, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        creaEsercizioButton = new JButton();
        creaEsercizioButton.setText("Crea esercizio");
        contentPane.add(creaEsercizioButton, new GridConstraints(1, 5, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(-1, 100), null, 0, false));
        final Spacer spacer7 = new Spacer();
        contentPane.add(spacer7, new GridConstraints(1, 4, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }

}
