package boundary;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.net.URL;

public class FormIntesaSport {
    private JPanel contentPane;
    private JButton cercaSessioniButton;
    private JButton creaSessioneButton;
    private JButton registraPrestazioniButton;
    private JLabel labelImmagine;

    private JFrame cercaSessioniFrame;
    private JFrame registraPrestazioniFrame;
    private JFrame creaSessioniFrame;
    private JFrame creaEsercizioFrame;

    public FormIntesaSport() {

        URL imgURL = getClass().getResource("/logo.png");

        if (imgURL != null) {
            ImageIcon iconaOriginale = new ImageIcon(imgURL);
            Image imgScalata = iconaOriginale.getImage().getScaledInstance(300, 300, Image.SCALE_SMOOTH);

            labelImmagine.setIcon(new ImageIcon(imgScalata));
        } else {
            System.err.println("Immagine non trovata! Controlla src/main/resources/");
        }

        cercaSessioniButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

                if (cercaSessioniFrame == null || !cercaSessioniFrame.isDisplayable()) {
                    FormCercaSessioniConFiltro formInserimento = new FormCercaSessioniConFiltro();
                    cercaSessioniFrame = formInserimento.apriFormCercaSessioni();
                    cercaSessioniFrame.setLocationRelativeTo(null);
                    cercaSessioniFrame.setVisible(true);
                } else {
                    cercaSessioniFrame.toFront();
                    cercaSessioniFrame.requestFocus();
                }
            }
        });

        registraPrestazioniButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

                if (registraPrestazioniFrame == null || !registraPrestazioniFrame.isDisplayable()) {
                    FormRegistraPrestazioni formRegistraP = new FormRegistraPrestazioni();
                    registraPrestazioniFrame = formRegistraP.apriFormRegistraPrestazioni();
                    registraPrestazioniFrame.setLocationRelativeTo(null);
                    registraPrestazioniFrame.setVisible(true);
                } else {
                    registraPrestazioniFrame.toFront();
                    registraPrestazioniFrame.requestFocus();
                }
            }
        });

        creaSessioneButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Se la finestra non esiste o è stata chiusa (non displayable)
                if (creaSessioniFrame == null || !creaSessioniFrame.isDisplayable()) {

                    // Istanziamo il form (che ora è un JFrame)
                    FormCreaSessioneAllenamento form = new FormCreaSessioneAllenamento();

                    // Lo assegniamo alla variabile di istanza della classe per tracciarlo
                    creaSessioniFrame = form;

                    creaSessioniFrame.setLocationRelativeTo(contentPane);
                    creaSessioniFrame.setVisible(true);
                } else {
                    // Se è già aperta, la porta in primo piano senza duplicarla
                    creaSessioniFrame.toFront();
                    creaSessioniFrame.requestFocus();
                }
            }
        });
    }

    public static void main(String[] args) {

        JFrame frame = new JFrame("Homepage Intesa Sport");

        FormIntesaSport mainFrame = new FormIntesaSport();

        frame.setContentPane(mainFrame.contentPane);

        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setSize(1000, 800);
        frame.setResizable(false);
        frame.pack();
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);


    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPane = new JPanel();
        contentPane.setLayout(new GridLayoutManager(4, 3, new Insets(0, 0, 20, 0), -1, -1));
        contentPane.setMaximumSize(new Dimension(400, 650));
        contentPane.setMinimumSize(new Dimension(400, 650));
        contentPane.setOpaque(true);
        contentPane.setPreferredSize(new Dimension(400, 650));
        registraPrestazioniButton = new JButton();
        registraPrestazioniButton.setFocusable(true);
        registraPrestazioniButton.setText("Registra prestazioni");
        contentPane.add(registraPrestazioniButton, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(-1, 100), null, 0, false));
        final Spacer spacer1 = new Spacer();
        contentPane.add(spacer1, new GridConstraints(1, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, new Dimension(20, -1), null, 0, false));
        final Spacer spacer2 = new Spacer();
        contentPane.add(spacer2, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, new Dimension(20, -1), null, 0, false));
        labelImmagine = new JLabel();
        labelImmagine.setDoubleBuffered(true);
        labelImmagine.setText("");
        contentPane.add(labelImmagine, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        cercaSessioniButton = new JButton();
        cercaSessioniButton.setText("Cerca sessioni");
        contentPane.add(cercaSessioniButton, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(-1, 100), null, 0, false));
        creaSessioneButton = new JButton();
        creaSessioneButton.setText("Crea sessione");
        contentPane.add(creaSessioneButton, new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(-1, 100), null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }

}
