package boundary;

import com.github.lgooddatepicker.components.DatePicker;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import controller.IntesaSport;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.time.LocalDate;
import java.util.List;
import java.awt.*;

public class FormCercaSessioniConFiltro {
    private JTextField textEmail;
    private JTextField textDisciplina;
    private JComboBox boxStatoSessione;
    private JButton caricaSessioniButton;
    private JTable table1;
    private JPanel panel;
    private DatePicker dataField;

    public FormCercaSessioniConFiltro() {

        caricaSessioniButton.addActionListener(e -> {
            String email = textEmail.getText();
            String disciplina = textDisciplina.getText();
            String statoString = (String) boxStatoSessione.getSelectedItem();
            LocalDate data = dataField.getDate();

            if (email == null || email.trim().isEmpty()) {
                JOptionPane.showMessageDialog(null,
                        "Il campo E-Mail Atleta è obbligatorio per effettuare la ricerca!",
                        "Errore Input",
                        JOptionPane.WARNING_MESSAGE);
                return;
            }

            List<String[]> righeDati = IntesaSport.visualizzaSessioniAssegnate(email, data, statoString, disciplina);

            String[] colonne = {
                    "ID", "Titolo", "Descrizione", "Data", "Durata prevista",
                    "Stato sessione", "Id dettaglio esercizio", "Descrizione esercizio", "Nome esercizio",
                    "Durata esercizio", "Ripetizioni esercizio"
            };

            DefaultTableModel model = new DefaultTableModel(colonne, 0);

            String ultimoIdSessione = "";

            for (String[] riga : righeDati) {
                String[] rigaCopia = new String[riga.length];
                System.arraycopy(riga, 0, rigaCopia, 0, riga.length);

                String attualeIdSessione = rigaCopia[0];

                if (attualeIdSessione != null && attualeIdSessione.equals(ultimoIdSessione)) {
                    rigaCopia[0] = "";
                    rigaCopia[1] = "";
                    rigaCopia[2] = "";
                    rigaCopia[3] = "";
                    rigaCopia[4] = "";
                    rigaCopia[5] = "";
                } else {
                    ultimoIdSessione = attualeIdSessione;
                }

                model.addRow(rigaCopia);
            }

            table1.setModel(model);

            // === BLOCCO DI CONFIGURAZIONE TABELLA IDENTICO A REGISTRA PRESTAZIONI ===
            table1.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
            table1.getColumnModel().getColumn(0).setPreferredWidth(40);
            table1.getColumnModel().getColumn(1).setPreferredWidth(120);
            table1.getColumnModel().getColumn(2).setPreferredWidth(180);
            table1.getColumnModel().getColumn(3).setWidth(90);
            table1.getColumnModel().getColumn(3).setPreferredWidth(90);
            table1.getColumnModel().getColumn(4).setPreferredWidth(110);
            table1.getColumnModel().getColumn(5).setPreferredWidth(110);
            table1.getColumnModel().getColumn(6).setPreferredWidth(140);
            table1.getColumnModel().getColumn(7).setPreferredWidth(180);
            table1.getColumnModel().getColumn(8).setPreferredWidth(120);
            table1.getColumnModel().getColumn(9).setPreferredWidth(110);
            table1.getColumnModel().getColumn(10).setPreferredWidth(130);
            table1.getTableHeader().setResizingAllowed(true);
            // ======================================================================
        });
    }

    public JFrame apriFormCercaSessioni() {

        JFrame frame = new JFrame("Cerca sessioni con filtro");

        frame.setContentPane(panel);

        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        frame.pack();
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);

        return frame;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel = new JPanel();
        panel.setLayout(new GridLayoutManager(5, 3, new Insets(10, 10, 15, 15), -1, -1));
        final Spacer spacer1 = new Spacer();
        panel.add(spacer1, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        final JLabel label1 = new JLabel();
        label1.setText("Stato sessione");
        panel.add(label1, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        boxStatoSessione = new JComboBox();
        final DefaultComboBoxModel defaultComboBoxModel1 = new DefaultComboBoxModel();
        defaultComboBoxModel1.addElement("-- Seleziona stato --");
        defaultComboBoxModel1.addElement("Assegnata");
        defaultComboBoxModel1.addElement("Completata");
        defaultComboBoxModel1.addElement("In corso");
        boxStatoSessione.setModel(defaultComboBoxModel1);
        panel.add(boxStatoSessione, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), new Dimension(200, -1), 0, false));
        final JLabel label2 = new JLabel();
        label2.setText("Data");
        label2.setVerticalAlignment(0);
        panel.add(label2, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));

        // === MODIFICATA LA SCROLLPANE AGGIUNGENDO IL RESTRITTANTE DELLE DIMENSIONI (PREFERITA E MASSIMA A 250) ===
        final JScrollPane scrollPane1 = new JScrollPane();
        panel.add(scrollPane1, new GridConstraints(4, 1, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(-1, 250), new Dimension(-1, 250), 0, false));

        table1 = new JTable();
        scrollPane1.setViewportView(table1);
        final JLabel label3 = new JLabel();
        label3.setText("E-Mail Atleta");
        panel.add(label3, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label4 = new JLabel();
        label4.setText("Disciplina");
        panel.add(label4, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 1, false));
        textDisciplina = new JTextField();
        textDisciplina.setText("");
        panel.add(textDisciplina, new GridConstraints(1, 1, 1, 2, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), new Dimension(200, -1), 0, false));
        textEmail = new JTextField();
        panel.add(textEmail, new GridConstraints(0, 1, 1, 2, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), new Dimension(200, -1), 0, false));
        caricaSessioniButton = new JButton();
        caricaSessioniButton.setText("Carica sessioni");
        panel.add(caricaSessioniButton, new GridConstraints(2, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, 30), new Dimension(150, 30), 0, false));
        dataField = new DatePicker();
        panel.add(dataField, new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel;
    }
}